site_name: WindListen 科技新闻
site_url: https://yanzhg.github.io/windlisten/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
  sidebar_width: 25rem

plugins:
  - search:
      lang: zh
      separator: '[\s\-\.，。、0-9]'
      prebuild_index: true
  - blog # 开启博客自动导航
nav:
  - 首页: index.md
  - 新闻汇总: posts/index.md # 只需要写目录首页，单篇新闻自动归入侧边栏

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yanzhg

extra_css:
  - assets/style.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js