site_name: WindListen 科技新闻
site_description: 每日自动采集互联网科技新闻
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight

# 固定导航分组，awesome-pages自动扫描posts内文件放入该分组
nav:
  - 首页: index.md
  - 今日新闻:
      - 汇总首页: posts/index.md
      - auto: posts

plugins:
  - search
  - awesome-pages